function ArtThink()
{
    var generateText= new Array("It's amazing and it's art because I said so.", "It's art because you don't think it's art.", "It's art because it's beautiful.","This is art because I say it is.", "All you need to know is that my work is amazing.", "If you aren't an art critic or philosopher, you just won't get it.", "It's art, so it means emotion, feelings.", "Go to art school for four years, study art history, write numerous papers that analyze the meaning behind different art movements, then take a look at my work and then you'll really know what it means.", "It represents the tragedy of trying to comprehend what it really means.", "If you think you understand it, you actually don't. Because that's how art works.", "This represents my view of the world and humanity.", "This represents society's fate.", "It's art, which means it's better than you.", "It's art, so it's important. That's all you need to know.", "You don't understand me because I'm an artist.", "I made this because I felt like it.", "Don't ask me why I made my work - I just did.", "This represents my soul.", "This represents my life.", "You don't understand it because it's art.", "The purpose of my work is confusion.", "I made this because I was bored.", "I don't know why I made this. Do you?", "Not getting my art is the whole point behind it.", "It speaks for itself.", "If you stare at it long enough, you should get it.", "If you don't get it, that actually means you got it.", "My art means everything.", "Only geniuses truly 'get' my work.", "I tried really hard...so it's art.", "Whatever, it's art and stuff.", "I made it so it must be art.", "Can you just pretend it's fantastic?", "It's the 'Emperor's New Clothes' of art.", "Can you pretend you get it?", "It doesn't matter what it represents. Don't worry about it.");
    var random = generateText[Math.floor(Math.random() * generateText.length)];
	if (random == generateText) {
		generateText.splice(random);
		}
    //alert(random);
    document.getElementById("text").innerHTML=random;
}
